version: '3.8'

services:
  db:
    image: postgres:15
    container_name: padel_db
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: padel_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@padel.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - db

  backend:
    build:
      context: ./backend-padel-stats-tracker
      dockerfile: Dockerfile
    container_name: padel_backend
    env_file: .env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - '3000:3000'
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend-padel-stats-tracker
      dockerfile: Dockerfile
    container_name: padel_frontend
    ports:
      - '5173:5173'
    depends_on:
      - backend

volumes:
  db_data:
    name: padel_db_data
