name: Backend CI

on:
  push:
    branches: [main, staging, production]
    paths:
      - 'backend-padel-stats-tracker/**'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    paths:
      - 'backend-padel-stats-tracker/**'
      - '.github/workflows/backend-ci.yml'
  workflow_dispatch:

jobs:
  lint-and-build:
    name: Lint & Build Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend-padel-stats-tracker
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'
          cache-dependency-path: backend-padel-stats-tracker/yarn.lock
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn build
